PYTHON=python
.PHONY: default
default:
	${MAKE} PYTHON=${PYTHON} -C compute-pi
	${MAKE} PYTHON=${PYTHON} -C gemv
	${MAKE} PYTHON=${PYTHON} -C gemm
	${MAKE} PYTHON=${PYTHON} -C ping-pong
	${MAKE} PYTHON=${PYTHON} -C thermal
